package main

import (
	"controllercontrol/camera"
	"controllercontrol/mappings"
	"fmt"
	"log"
	"math"
	"time"

	"github.com/0xcafed00d/joystick"
)

func main() {
	err := run()
	if err != nil {
		log.Fatalln("Error running program!", err)
	}
}

func run() error {
	js, err := joystick.Open(0)

	if err != nil {
		return err
	}
	fmt.Printf("Joystick Name: %s\n", js.Name())
	fmt.Printf("   Axis Count: %d\n", js.AxisCount())
	fmt.Printf(" Button Count: %d\n", js.ButtonCount())

	handler, err := camera.NewProtocolHandler("tcp://172.17.52.113:1259")
	if err != nil {
		return err
	}

	var panSpeed int16 = 10
	var tiltSpeed int16 = 10
	step := float64(10)

	for {
		state, err := js.Read()
		if err != nil {
			log.Println("Error reading from Joystick!", err)
			time.Sleep(100 * time.Millisecond)
			continue
		}

		fmt.Printf("Axis Data: %v\n", state.AxisData)
		fmt.Printf("Button Data: %v\n", state.Buttons)
		fmt.Printf("Button States: [%v, %v, %v, %v]\n",
			GetButtonState(state.Buttons, mappings.XboxOneA),
			GetButtonState(state.Buttons, mappings.XboxOneB),
			GetButtonState(state.Buttons, mappings.XboxOneX),
			GetButtonState(state.Buttons, mappings.XboxOneY),
		)
		pan := float64(state.AxisData[mappings.XboxLeftStickX]) / mappings.XboxStickMax
		panOffset := int16(pan * step)
		tilt := float64(state.AxisData[mappings.XboxLeftStickY]) / mappings.XboxStickMax
		tiltOffset := -1 * int16(tilt*step)

		byteSlice := camera.PanTilt(panSpeed*(1+int16(pan)*4), tiltSpeed*(1+int16(tilt)*4), panOffset, tiltOffset, true)
		if err != nil {
			return err
		}

		if (tiltOffset != 0 && math.Abs(float64(tiltOffset)) > mappings.XboxDeadzone*step) || (panOffset != 0 && math.Abs(float64(panOffset)) > mappings.XboxDeadzone*step) {
			handler.SendPacketYolo(byteSlice)
		}

		fmt.Printf("Pan Position: %d\n", panOffset)
		fmt.Printf("Tilt Position: %d\n", tiltOffset)

		fmt.Printf("Generated byte slice: % x\n", byteSlice)
		time.Sleep(50 * time.Millisecond)
	}
	js.Close()

	return nil
}
